### ISSUE TITLE
希望日後能擴充繁體中文(big5)常用漢字

### ISSUE THREAD

**Issue by jisbig5** [coz-m/MPLUS_FONTS#11]
希望日後能擴充繁體中文(big5)常用漢字

**Comment by coz-m** [comment]
Currently, it is difficult to deal with Chinese because the completion of the JIS level-2 kanji set is also being postponed.
You are free to modify this font and create derivative fonts according to the SIL Open Font License, and I am happy for you to do so. Please consider doing so.
