### ISSUE TITLE
Please add ExtraLight and SemiBold instances

### ISSUE THREAD

**Issue by thlinard** [coz-m/MPLUS_FONTS#14]
Hi,

I saw you have submitted your typefaces to add them to Google Fonts. Because of the specs:

> When a variable font is onboarded to Google Fonts, we will provide instantiated static fonts for legacy applications. Thus, bear in mind Google’s API will automatically create all the 100x weights along the used range of the axis when producing static fonts, whether or not they are included in the designer's original design space.
https://github.com/googlefonts/gf-docs/tree/main/Spec#stat-table

Your VFs will miss two weights compared to their static version, which will pass them off as a diminished version of the static fonts in applications offering VF support but without axis control slider (instances-only support, like Microsoft or Apple applications).

So, please add an ExtraLight instance and a SemiBold instance.

**Comment by aaronbell** [comment]
One thing I don't quite understand—in addition to the variable font, we provided static instances of all the weights that Coji wanted in the font—so will GF *still* generate these 100x weights along the used range?

**Comment by thlinard** [comment]
> One thing I don't quite understand—in addition to the variable font, we provided static instances of all the weights that Coji wanted in the font—so will GF _still_ generate these 100x weights along the used range?

Indeed! Unless they've been manually hinted, I believe. But otherwise, no exception. I opened issue https://github.com/google/fonts/issues/3411 for that. You can easily verify by taking an example from the list, Mulish.

Static files are here (no Medium font, no Medium instance in VF): https://github.com/google/fonts/tree/main/ofl/mulish/static

Medium instance in https://fonts.google.com/specimen/Mulish (and Medium static file downloaed in the zip file offered, but no Medium instance in the VF file).

**Comment by thlinard** [comment]
Btw, because of https://github.com/google/fonts/issues/2616 you should at least keep statics files in your own repository, this can help users.

**Comment by aaronbell** [comment]
I believe that this issue can be closed as the font weights were added to the font.
