### ISSUE TITLE
Mplus Code Latin not recognized as monospace on Windows

### ISSUE THREAD

**Issue by ttyrakow** [coz-m/MPLUS_FONTS#18]
In some applications (e.g. mintty, Embarcadero RAD Studio) on MS Windows (tested on Win 10 pro 64bit with TTF version of the fonts), Mplus Code Latin is not available in the font list. Those are apps, which support only monospace fonts, and somehow Mplus Code Latin is not recognized as such. The older M+ 1mn font is recognized properly and is available. Other apps, (like VS Code), where you just type in the name of the font to use (instead of choosing from the list), don't have any issues with the font. It's well visible e.g. in Visual Studio 2019, which bolds out monospace fonts on the list, and Mplus Code is not bolded (M+ 1mn is).
![fontlist1](https://user-images.githubusercontent.com/51198662/121519607-339b0c80-c9f2-11eb-8bdc-a28a1a573989.png)
![fontlist2](https://user-images.githubusercontent.com/51198662/121519635-3990ed80-c9f2-11eb-90b5-8f4769a6f5d4.png)

**Comment by ttyrakow** [comment]
Just a quick followup: in some cases changing config files (.minttyrc for example) and manually typing the font name solves the problem (the font works in mintty, it's just not available on the font list). In some other cases however it doesn't (e.g. RAD Studio doesn't have easily accessible config).

**Comment by coz-m** [comment]
Thank you for pointing out the problem.
It's late, but we've updated the font file. We would be glad if you try again.

**Comment by ttyrakow** [comment]
The new version works great and is available (recognized as monospace) in all apps I could think of, including mintty, Visual Studio 2019 (see attached screenshot: all Mplus Code Latin variants are bolded out as being monospace), Embarcadero RAD Studio, and even classic Windows command prompt (which is very picky about the fonts you can set in it). Great work, and btw. I love the 60 variant - the old M+ 1mn was a bit too condensed IMHO (but beautiful and standing out nonetheless).
![vs2019-mplus](https://user-images.githubusercontent.com/51198662/122131359-5cc7fc80-ce39-11eb-8dcd-a9f69f90d8a1.png)

**Comment by coz-m** [comment]
Thank you for your confirmation.  I'm happy to be able to fix it.

**Comment by inferiorhumanorgans** [comment]
```
$ for i in ~/MPLUS_FONTS/fonts/{ttf,otf}/*.{ttf,otf}; do variant-inspect -p $i; done | grep -i code | grep -v true
Mplus1Code-Bold.ttf: M PLUS 1 Code Bold (Version 1.006) mono = false
Mplus1Code-ExtraLight.ttf: M PLUS 1 Code ExtraLight (Version 1.006) mono = false
Mplus1Code-Light.ttf: M PLUS 1 Code Light (Version 1.006) mono = false
Mplus1Code-Medium.ttf: M PLUS 1 Code Medium (Version 1.006) mono = false
Mplus1Code-Regular.ttf: M PLUS 1 Code Regular (Version 1.006) mono = false
Mplus1Code-SemiBold.ttf: M PLUS 1 Code SemiBold (Version 1.006) mono = false
Mplus1Code-Thin.ttf: M PLUS 1 Code Thin (Version 1.006) mono = false
Mplus1Code-Bold.otf: M PLUS 1 Code Bold (Version 1.006) mono = false
Mplus1Code-ExtraLight.otf: M PLUS 1 Code ExtraLight (Version 1.006) mono = false
Mplus1Code-Light.otf: M PLUS 1 Code Light (Version 1.006) mono = false
Mplus1Code-Medium.otf: M PLUS 1 Code Medium (Version 1.006) mono = false
Mplus1Code-Regular.otf: M PLUS 1 Code Regular (Version 1.006) mono = false
Mplus1Code-SemiBold.otf: M PLUS 1 Code SemiBold (Version 1.006) mono = false
Mplus1Code-Thin.otf: M PLUS 1 Code Thin (Version 1.006) mono = false
```

I don't know if this is intentional but the Mplus1Code fonts (but not the 50 or 60 variants) are not marked as monospace fonts in either the `post` or `os/2` tables.

**Comment by mancoi** [comment]
Not sure if I should create another issue, but for me, the M+ Code Latin font is showing up in the Windows 10 Command Prompt/PowerShell fonts list, but the M+ Code font isn't.

**Comment by coz-m** [comment]
Sorry for the late reply.
The M+ Code font contains Japanese glyphs that are twice as wide as Latin glyphs, so this may be the reason.
