### ISSUE TITLE
Line height on Mplus Code Latin is too large

### ISSUE THREAD

**Issue by kkga** [coz-m/MPLUS_FONTS#23]
The current line height on `Mplus Code Latin 50` and `Mplus Code Latin 60` is too large for a coding font that doesn't include any large characters like the rest of the family.

I've been experimenting with [font-line](https://github.com/source-foundry/font-line) to test different values for UPM percentage and got a much more compact yet readable output with the value of `1.16` (same as reported by font-line for Cascadia Code).

Here's the comparison of 3 fonts (font-size adjusted to have identical horizontal metrics) with UPM values reported by font-line:

- Left: Cascadia Mono (UPM 1.16)
- Center: Mplus Code Latin 50 (Original, UPM 1.45)
- Right: Mplus Code Latin 50 (Modified with font-line, UPM 1.16)

![image](https://user-images.githubusercontent.com/1460122/133798766-cc7711ab-f3d2-4e8c-aff1-2ee96e69fc82.png)

**Comment by coz-m** [comment]
Thank you for your wonderful suggestions.
We're just about to publish it on Google Fonts, but it turns out that it's still in time, so we'll adopt your point.
