### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by dtvgit** [coz-m/MPLUS_FONTS#27]
重宝させて頂いております
MPlus1-RegularとMPlus1-SemiBoldの中間の太さのフォントがあると嬉しいです

**Comment by coz-m** [comment]
返事が遅くなってすみません。Regular と SemiBold の中間には Medium がありますが、せっかくの Variable フォントなのでさらに中間の太さをお求めであれば、Mplus1[wght].ttf を利用して

1. web 上での使用であれば css で設定。
2. Adobe Illustrator、Photoshop などであればバリアブルフォント用スライダーで調整。

することができます。
以前は https://fontgauntlet.com の web サービスで Variable フォントを任意に調整して「Generate Static Font File」することができたと思うのですが、今試してみると日本語フォントではエラーになってしまいました。他に同様のサービスがあるのかどうかは見つけることができませんでした。

**Comment by dtvgit** [comment]
MPlus1-Mediumがあったのを見落としていました。今試したところちょうど良い感じになりました。お手数お掛け致しました。

**Comment by coz-m** [comment]
良かったです。
