### ISSUE TITLE
Weighting for MPlus Code

### ISSUE THREAD

**Issue by aaronbell** [coz-m/MPLUS_FONTS#3]
Hello!

Writing the script for building the fonts and had a question regarding MPLUS Code. Based on my understanding, you're looking for something like this:

Variant | Latin set | Kana Set | Kanji Set
------------ | ------------- | ------------- | ------------- 
MPlus Code Latin | MPlus Code | None | None
MPlus Code JP | MPlus Code | MPlus 1 Kana | MPlus Kanji

The "MPlus Code Latin" is a variable font with weight and width axis (50 to 60), and MPlus Code JP is similarly a variable font with weight axis. 

For the JP version, the current set of masters has a differing set of weights than the MPlus 1 and Kanji set do, with MPlus Code generally being lighter than the corresponding Japanese glyphs:

<img width="1066" alt="Screen Shot 2021-04-29 at 3 56 38 PM" src="https://user-images.githubusercontent.com/8460297/116629861-0e9d7f00-a907-11eb-9b84-d067f8c215a2.png">
<img width="1076" alt="Screen Shot 2021-04-29 at 4 03 25 PM" src="https://user-images.githubusercontent.com/8460297/116629864-10674280-a907-11eb-8778-1af1a8cfb9e0.png">
<img width="1042" alt="Screen Shot 2021-04-29 at 4 04 21 PM" src="https://user-images.githubusercontent.com/8460297/116629867-12310600-a907-11eb-86e5-5c4fe6f4bcdd.png">

I anticipate that you'll want the weights to align across the three scripts, so how do you want me to resolve this? Shall I generate an instance of the Kana / Kanji set that aligns with the Regular and Bold? Or do you want to leave it "as is"?

**Comment by coz-m** [comment]
Hi Aaron,

- In the case of MPlus Code JP, I was thinking of limiting the Latin set to "code 50" so that 1 Japanese glyph corresponds to the width of 2 Latin glyphs. What do you think, Aaron? Should I have a combination of "code60" and Japanese glyphs that is easier to read even if the 50: 100 balance is lost?

- MPlus Code is considering a 5-weight deployment from Thin to Bold. Japanese glyphs Black and Extra Bold weights are not used.

Thanks,
Coji

**Comment by aaronbell** [comment]
For Code JP, I suggest using just "code 50" since the intent is to keep glyphs on a monospace grid. 

As for the weights, I understand your intent—I'll export out instances of the Regular and Bold to match with the Code weighting. Thanks!

**Comment by coz-m** [comment]
Thank you for your advice. Then, as originally planned, please support only "code 50" for MPlus Code JP.

Thanks,
Coji

**Comment by coz-m** [comment]
@aaronbell 
Thomas Linard has asked me to add 2 instances to submit the variable font to Google Fonts, but these variable fonts are generated by your script, so how to fix them? I don't understand. Will you support me?

https://github.com/coz-m/MPLUS_FONTS/issues/14

**Comment by aaronbell** [comment]
Either update the glyphs sources with the two new instances, or let me know where they should be in the weight axis, and I can update the files.

**Comment by coz-m** [comment]
Thomas Linard says, "So, please add an ExtraLight instance and a SemiBold instance."

**Comment by aaronbell** [comment]
Yes, we need to set what the weight values will be for the ExtraLight and SemiBold instances:

<img width="488" alt="MPLUS-1___Instances" src="https://user-images.githubusercontent.com/8460297/119354143-93569100-bc58-11eb-8f3b-2d539e1580ec.png">

Either you can do that, or tell me what you want and I'll update them.

**Comment by coz-m** [comment]
Hmmm, I don't understand well, but can you make settings that do not affect the current font content?

**Comment by aaronbell** [comment]
Yes. I’ll take care of it for you :)

**Comment by coz-m** [comment]
I'm sorry you are very busy, thank you.
