### ISSUE TITLE
Metrics issue? The CSS `ch` unit has the wrong width when using this font

### ISSUE THREAD

**Issue by tremby** [coz-m/MPLUS_FONTS#31]
I'm loading the "M PLUS ROUNDED 1C" font from Google Fonts.

See https://codepen.io/tremby/pen/abVBQXx

The cyan background should exactly cover one zero, and the space around it such that it could be repeated with no gap and cover the next 0 exactly the same.

It is too small on Firefox, and *much* too small on Chrome. I've tried in Linux, Mac, and Windows, and see the same on each platform.

**Comment by coz-m** [comment]
Sorry for the late reply." The "M PLUS ROUNDED" font is a derivative of the "M+ FONT" font created by a third party, so I have no editorial control over it.
