### ISSUE TITLE
フォント名が "M PLUS 1[空白][空白]Code" のようになっている

### ISSUE THREAD

**Issue by akihironagai** [coz-m/MPLUS_FONTS#32]
M PLUS 1[空白]Code（1とCodeの空白が1つ）とあるべきところが、
M PLUS 1[空白][空白]Code（1とCodeの空白が2つ）になっているようです。

Mplus1Code-Bold.ttf などのバリアブルフォントではないフォントでこの現象を確認しました。

![Bad](https://user-images.githubusercontent.com/77012577/157863979-48f0b348-5820-4b0a-b5c6-b931ba21cdfe.png)

![Good](https://user-images.githubusercontent.com/77012577/157863963-5a151973-2309-49c9-8bfc-5697aa52d301.png)

**Comment by coz-m** [comment]
ご指摘ありがとうございます。こちらの環境（MacOS + Illustrator、Terminal）でも確認できました。
フォントの元データではなく、ビルドファイル内のミスのようなので自分には直接修正できませんが、contributor に連絡してみます。
ご連絡が遅くなって申し訳ありませんでした。

**Comment by coz-m** [comment]
以下の通り修正していただけました。
ご指摘ありがとうございました。

https://github.com/coz-m/MPLUS_FONTS/pull/33
