### ISSUE TITLE
zero character, and underscore character

### ISSUE THREAD

**Issue by nashpatty** [coz-m/MPLUS_FONTS#34]
@coz-m hey, great work on the font. I love the stylistic choices.
I had a question about the zero character, and the underscore character.

For the zero character, is the dot intentionally aligned closer to the top, rather than centered? (or is it centered and my vision is going crazy? :no_mouth:)

Secondly, could there be a little space around the underscore character, so more than one underscore doesn't look like a continuous line? Several programming languages have syntax with multiple underscores (dunder etc.) and it would be helpful to see how many characters are present at a glance.

Examples of both questions:
<img width="271" alt="Screen Shot 2022-04-20 at 1 12 16 AM" src="https://user-images.githubusercontent.com/28615881/164155562-9d9c8ae7-ce38-4622-a862-817512f3a9e1.png">

**Comment by coz-m** [comment]
Sorry for the late reply.

Normally, if the dots are centered exactly, they will feel subscripted and unstable.
To adjust for this visual sensation, it is intentionally placed slightly superscript.

As you say, in fixed-width fonts for programming, it would be better to create a gap at both ends of the underscore.
I will fix the underscore design; it will take some time to be reflected in Google Fonts, so in the meantime I will refer you to the download link for the font files.

**Comment by nashpatty** [comment]
Thanks for your detailed response. I'm looking forward to the changes.

**Comment by coz-m** [comment]
M PLUS Code Latin font files with underscore on both sides are available at the following URL.
https://github.com/mplusfonts/mplusfonts.github.com/tree/master/download
In the meantime, please download and use it from here.
<img width="496" alt="Screen Shot 2022-05-01 at 11 48 13" src="https://user-images.githubusercontent.com/55127265/166130249-b73a6af3-9cf5-4b0f-9465-769cef87ae41.png">
