### ISSUE TITLE
Zero is similar to eight

### ISSUE THREAD

**Issue by pit00** [coz-m/MPLUS_FONTS#35]
![image](https://user-images.githubusercontent.com/12652738/164344239-7b85e02a-1391-47ef-a3c1-b5edbc1d1c78.png)

**Comment by coz-m** [comment]
Sorry for the late reply.
I consider it more important to distinguish between a zero and a capital O.
Also, the reason for not making it zero with a slash is to distinguish it from Ø.

**Comment by pit00** [comment]
Understandable, but maybe this variation "solve" both problems:
![image](https://user-images.githubusercontent.com/12652738/165657918-86a34500-8c7f-484f-a1ce-439d7d2696ad.png)

**Comment by coz-m** [comment]
Thank you for your meaningful suggestions.
I will make a prototype font later.

**Comment by coz-m** [comment]
Sorry for the delay. I have prepared a prototype font file at the URL below. I hope you will try it.
https://github.com/mplusfonts/mplusfonts.github.com/tree/master/download

<img width="602" alt="Screen Shot 2022-06-08 at 10 56 53" src="https://user-images.githubusercontent.com/55127265/172515849-975522bc-649e-4e29-9010-2a45b46c5996.png">

**Comment by Vistaus** [comment]
> Sorry for the delay. I have prepared a prototype font file at the URL below. I hope you will try it. https://github.com/mplusfonts/mplusfonts.github.com/tree/master/download
> 
> <img alt="Screen Shot 2022-06-08 at 10 56 53" width="602" src="https://user-images.githubusercontent.com/55127265/172515849-975522bc-649e-4e29-9010-2a45b46c5996.png">

I love it! I've immediately set it as my default terminal font. Thanks a bunch! :)

**Comment by coz-m** [comment]
Thank you very much for your meaningful suggestions.
Until updated in Google Fonts, please use the download link provided previously.
