### ISSUE TITLE
Ligatures don't work in Visual Studio Code

### ISSUE THREAD

**Issue by cmarincia** [coz-m/MPLUS_FONTS#36]
Hi Coji!
I have a problem in VS Code with M+1Code font. The ligatures are not working.
I used the `otfinfo` command to check the features:
```bash
[~/.fonts/MPLUS_FONTS] $ otfinfo -f Mplus1Code-Regular.ttf
aalt	Access All Alternates
case	Case-Sensitive Forms
ccmp	Glyph Composition/Decomposition
dlig	Discretionary Ligatures
frac	Fractions
jp04	JIS2004 Forms
liga	Standard Ligatures
mark	Mark Positioning
mkmk	Mark to Mark Positioning
ordn	Ordinals
pnum	Proportional Figures
sups	Superscript
tnum	Tabular Figures
```
In VS Code settings I tried both:
```
 "editor.fontLigatures": true
```
and
```
"editor.fontLigatures": "'liga'"
```
and none seems to enable the ligatures for the MPlus1Code font. This doesn't reproduce with other fonts like FiraCode or JetBrainsMono.

![image](https://user-images.githubusercontent.com/35623921/166336313-c7cf3337-c55d-4199-944b-41785b09d092.png)

**Comment by coz-m** [comment]
Sorry, but with fixed-width fonts, I do not use the ligatures feature because I want to count the number of characters accurately.

**Comment by L1ghtingBolt** [comment]
Would it be possible to add ligatures at least as a version?
