### ISSUE TITLE
Unicode and Nerd Fonts

### ISSUE THREAD

**Issue by pit00** [coz-m/MPLUS_FONTS#37]
I'm missing a bunch of unicode fonts, they appear as blank squares.
Also, any way to extend the support for Nerd Fonts (or a way to manually patch)?

**Comment by ran-dall** [comment]
There is a Nerd font for M+. However, I'm not sure how up-to-date they are. https://www.nerdfonts.com/font-downloads

![MPlus Nerd Font](https://user-images.githubusercontent.com/17261190/169148461-178fd6b3-70c3-4d2a-9b55-fdb01325c523.svg)

**Comment by pit00** [comment]
> There is a Nerd font for M+. However, I'm not sure how up-to-date they are. https://www.nerdfonts.com/font-downloads
> 
> ![MPlus Nerd Font](https://user-images.githubusercontent.com/17261190/169148461-178fd6b3-70c3-4d2a-9b55-fdb01325c523.svg)

Oh, the titles are images... I was using the search tool lol.
Thx anyway!
