### ISSUE TITLE
M PLUS 1 Latinバージョンがリリースされますか

### ISSUE THREAD

**Issue by hingbong** [coz-m/MPLUS_FONTS#38]
今のM PLUS 1は漢字がありますし、時々中国語の漢字を錯乱しますから、ピュアLatinバージョンが必要と思います。
日本語上手くないです、すみません。

**Comment by hingbong** [comment]
または、既存のjis漢字に基づいて、他の漢字を追加します、例えば、中国語の漢字

**Comment by coz-m** [comment]
ご提案ありがとうございます。
とりあえず、後ほど M PLUS 1 Latin バージョンを作成してみます。

**Comment by hingbong** [comment]
ありがとうございます

**Comment by coz-m** [comment]
遅くなってすみませんでした。暫定的に漢字を含まない（かな文字は含まれています）フォントファイルを用意しました。
https://github.com/mplusfonts/mplusfonts.github.com/tree/master/download/No_Kanji_glyphs/

**Comment by hingbong** [comment]
試してみました。中国語の場合には別のフォントで、漢字は邪魔にならないです。日本語の場合にはきれいな仮名が表現しています。ありがとうございます。
