### ISSUE TITLE
M+ 1m for programmers

### ISSUE THREAD

**Issue by sstativa** [coz-m/MPLUS_FONTS#39]
Is there a plan to include original M+ 1m for programmers? Personally, M+ 1m looks way better than M Plus Code. 
Imho, C and S of the new font are "overloaded" with useless "tick".

M Plus Code (left) M+ 1m (right)

![new-old](https://user-images.githubusercontent.com/3362679/185264976-7a5669cf-1718-4b1c-9d24-1238041ceef7.png)

**Comment by coz-m** [comment]
Sorry for the late reply. I would like to keep a separate website for
"M+ 1m" and "M Plus Code" because I want to make a clear distinction
between the old and new fonts.

Please continue to use the "M+ 1m" font as before at
"http://mplus-fonts.osdn.jp".
