### ISSUE TITLE
Ready for build?

### ISSUE THREAD

**Issue by aaronbell** [coz-m/MPLUS_FONTS#4]
Hi Coji,

The build process is ready to go (I've got all variants of the font building locally), so wanted to confirm with you that the Latin glyphs files are ready on your end. There'll likely be some additional small fixes I need to do on the files to finalize things and I don't want to cause merge issues!

Thanks

**Comment by coz-m** [comment]
Hi Aaron,

Thank you for your work. The last file was updated four days ago.  Please work with this file.

Thanks.

**Comment by aaronbell** [comment]
👍
