### ISSUE TITLE
迚 kanji?

### ISSUE THREAD

**Issue by TheChilliPL** [coz-m/MPLUS_FONTS#40]
The 迚 kanji character seems to not be a part of this font:

![image](https://user-images.githubusercontent.com/18823939/189764835-15e71893-01f2-4214-a0df-d2546d2e869a.png)

![image](https://user-images.githubusercontent.com/18823939/189764879-d804d365-fe54-4944-93e6-7fb5f50bdfa4.png)

Any reason why it's not included?

**Comment by coz-m** [comment]
Additional Kanji glyph "迚 (U+8FDA)" has been created. This will be reflected in the next update.
Tentative Kanji font files are available at the following URL. Please feel free to use it.

https://github.com/mplusfonts/mplusfonts.github.com/tree/master/download/Kanji_glyphs

<img width="1552" alt="Screen Shot 2022-09-19 at 14 02 23" src="https://user-images.githubusercontent.com/55127265/190956580-c9e28f63-9103-4520-b749-fedf848cce2e.png">
