### ISSUE TITLE
Github version lacks Cyrillic glyphs

### ISSUE THREAD

**Issue by yuki0iq** [coz-m/MPLUS_FONTS#41]
![image](https://user-images.githubusercontent.com/44705138/199187926-f192017c-dc63-41ea-bd53-f22adb1fa594.png)
[link for this image](https://fonts.google.com/?query=Coji+Morishita&preview.text=All%20human%20beings%20are%20born%20free%20and%20equal%20in%20dignity%20and%20rights.%20They%20are%20endowed%20with%20reason%20and%20conscience%20and%20should%20act%20towards%20one%20another%20in%20a%20spirit%20of%20brotherhood.%20%D0%92%D1%81%D0%B5%20%D0%BB%D1%8E%D0%B4%D0%B8%20%D1%80%D0%BE%D0%B6%D0%B4%D0%B0%D1%8E%D1%82%D1%81%D1%8F%20%D1%81%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D1%8B%D0%BC%D0%B8%20%D0%B8%20%D1%80%D0%B0%D0%B2%D0%BD%D1%8B%D0%BC%D0%B8%20%D0%B2%20%D1%81%D0%B2%D0%BE%D0%B5%D0%BC%20%D0%B4%D0%BE%D1%81%D1%82%D0%BE%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%20%D0%B8%20%D0%BF%D1%80%D0%B0%D0%B2%D0%B0%D1%85.%20%D0%9E%D0%BD%D0%B8%20%D0%BD%D0%B0%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D1%8B%20%D1%80%D0%B0%D0%B7%D1%83%D0%BC%D0%BE%D0%BC%20%D0%B8%20%D1%81%D0%BE%D0%B2%D0%B5%D1%81%D1%82%D1%8C%D1%8E%20%D0%B8%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B%20%D0%BF%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0%D1%82%D1%8C%20%D0%B2%20%D0%BE%D1%82%D0%BD%D0%BE%D1%88%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B4%D1%80%D1%83%D0%B3%20%D0%B4%D1%80%D1%83%D0%B3%D0%B0%20%D0%B2%20%D0%B4%D1%83%D1%85%D0%B5%20%D0%B1%D1%80%D0%B0%D1%82%D1%81%D1%82%D0%B2%D0%B0.&preview.size=13&preview.text_type=custom)

OSDN version of M+ has Cyrillic glyphs, whereas GitHub version does not. Was this intended?

**Comment by coz-m** [comment]
Sorry for the late reply.

Only redesigned glyphs are available on GitHub.
# Except for the Kanji glyphs.
I am currently working on variations of hiragana, katakana, and basic alphabet glyphs, so the Cyrillic glyphs will be added much later.
