### ISSUE TITLE
Are there any plans on supporting Chinese, Greek and Cyrillic?

### ISSUE THREAD

**Issue by True0rFa1se** [coz-m/MPLUS_FONTS#42]

**Comment by coz-m** [comment]
Sorry for the late reply. At this time I do not plan to support the languages you suggest, but I have addressed Greek and Cyrillic to some extent in previous versions.

https://fonts.google.com/specimen/M+PLUS+1p
http://mplus-fonts.osdn.jp/about-en2.html
