### ISSUE TITLE
Are there any plans for stylistic sets for letters s and c?

### ISSUE THREAD

**Issue by enriqueMartinezInter** [coz-m/MPLUS_FONTS#44]
Hi! first of all I love MPlus Code 60 for developers! I was wondering is there any chance letters s and c to be completely sans-serif or at least get some stylistic sets to have the option of hide the top end of both of them?

Thank you and great work!

**Comment by coz-m** [comment]
I am glad you are using the M PLUS Code font.

The "C" and "S" serifs are just design accents, so I have no plans for variations at this time. I apologize for the inconvenience.

There is an older version of M+ FONTS on OSDN that is 50% wider, but has a more standardized glyph design.
http://mplus-fonts.osdn.jp/about-en2.html

You can also check these code fonts out if you like.
http://mplus-fonts.osdn.jp/design.html#mplus_m1
http://mplus-fonts.osdn.jp/design.html#mplus_m2
http://mplus-fonts.osdn.jp/design.html#mplus_mn1
