### ISSUE TITLE
installing using nerdfonts 

### ISSUE THREAD

**Issue by nbari** [coz-m/MPLUS_FONTS#46]
I am installing the font in Linux using https://github.com/ryanoasis/nerd-fonts/blob/master/install.sh MPlus, the font works and I have all the icons/Glyphs,  but by doing the same in macOS I can't find or get the same style from `M+ 1m Nerd Font Complete.ttf`:

![Screenshot from 2023-07-03 23-20-22](https://github.com/coz-m/MPLUS_FONTS/assets/364199/4a98faf7-45bf-4a63-aded-a393f0001534)

Instead of the 0 with the / I get a 0 with a dot, but for an unknown reason differs, any suggestions or advice about how to have the font across systems?

In both systems I use alacrity but still notice differences, In Mac OS the font looks like this:

<img width="794" alt="Screenshot 2023-07-04 at 08 23 33" src="https://github.com/coz-m/MPLUS_FONTS/assets/364199/81929011-55fb-418b-bfa6-2fbb2bd85b81">

But can't make it look like the original M+ including all the icons:

<img width="786" alt="Screenshot 2023-07-04 at 08 25 25" src="https://github.com/coz-m/MPLUS_FONTS/assets/364199/cb368898-0556-442a-b541-94236d334ddc">

**Comment by nbari** [comment]
I think is related to this https://github.com/ryanoasis/nerd-fonts/commit/1868c68c8b70e064a70e0653671f04cc5aac478b, after that commit the `M+ 1m Nerd Font Complete.ttf` is not installed anymore

**Comment by zhengpd** [comment]
I also like a monospaced version of `M+1` instead of `M+1 Code`, but don't know why it's gone.

**Comment by coz-m** [comment]
Since OSDN seems to be unstable, the final version of the old design is available at the following URL.
Please feel free to use it.

https://github.com/coz-m/MPLUS_FONTS/blob/master/obsolete/mplus-TESTFLIGHT-063a.tar.xz
