### ISSUE TITLE
Is there any chance to also have M Plus Bitmap fonts in this repository or google fonts?

### ISSUE THREAD

**Issue by lethefrost** [coz-m/MPLUS_FONTS#47]
Since the download link in [this page](https://mplus-fonts.osdn.jp/mplus-bitmap-fonts/download/index.html) is no longer working - Latest Release :   [M+ BITMAP FONTS 2.2.4](http://downloads.osdn.jp/mplus-fonts/5030/mplus_bitmap_fonts-2.2.4.tar.gz). 

I am wondering if it would be possible to have the bitmap families also move to this repo or google fonts?

Thank you so much for making the amazing fonts!

**Comment by coz-m** [comment]
Sorry for the late reply.
I have prepared the following link for you to use at your leisure.

https://github.com/coz-m/MPLUS_FONTS/blob/master/obsolete/mplus_bitmap_fonts-2.2.4.tar.gz

**Comment by andy0130tw** [comment]
The obsolete folder is removed, so I think it is worthwhile to save the permalink here: https://github.com/coz-m/MPLUS_FONTS/blob/5403ff7cea36c0328cec1ff0191f4164c93278ea/obsolete/mplus_bitmap_fonts-2.2.4.tar.gz
