### ISSUE TITLE
漢字のない M PLUS 1 バージョンではバリアブル フォントが提供されますか?

### ISSUE THREAD

**Issue by hingbong** [coz-m/MPLUS_FONTS#48]
お邪魔します、すみません。
漢字のない M PLUS 1 バージョンではバリアブル フォントが提供されますか?
今の漢字のない M PLUS 1 バージョンは普通のフォントですが、バリアブルフォントは占有スペースを小さくできるので、漢字のない M PLUS 1 バージョンのバリアブル フォントが欲しいです。
よろしくお願いいたします。

**Comment by coz-m** [comment]
大変お待たせしてしまい、申し訳ありませんでした。
https://github.com/coz-m/MPLUS_FONTS/tree/master/supplements/remove_kanji_glyphs
にて、M PLUS 1/2 の漢字を除去したバリアブルフォントを用意しました。ご確認お願いいたします。

**Comment by hingbong** [comment]
ありがとうございます。
