### ISSUE TITLE
Please reupload "M+ 1m/2m" families

### ISSUE THREAD

**Issue by duanemoody** [coz-m/MPLUS_FONTS#53]
I prefer the simpler designs in M+ 1m and M+ 2m to those in M+ 1 Code, even if 1m/2m are no longer actively being developed; 1m is my default font in VS Code. 

I install these fonts on MacOS using `brew`, and updates request I uninstall the older `font-mplus` package because it's been replaced by two newer packages. Unfortunately those two only install `MPLUS1[wght].ttf` and `MPLUS2[wght].ttf` and not even the monospace fonts still up in this repository. I will inform them of this problem separately, but if the 1m/2m fonts were restored first that would help me.

Thank you again for your work designing these fonts.

**Comment by coz-m** [comment]
Sorry for the delay in responding. Please feel free to use the link included below.
https://github.com/coz-m/MPLUS_FONTS/blob/master/obsolete/mplus-TESTFLIGHT-063b.tar.gz
