### ISSUE TITLE
半角カナの「ｺ」が「ｺ　」と描画される

### ISSUE THREAD

**Issue by nai-kon** [coz-m/MPLUS_FONTS#55]
お邪魔します。MPlus 2p系フォントで半角カナの`ｺ`を描画すると後ろに隙間が入ります。
これは仕様になりますか。ご確認お願いいたします。

https://fonts.adobe.com/fonts/m-plus-2p
![image](https://github.com/user-attachments/assets/a9ea4991-cc5f-47e8-9835-c520d3df59c3)

**Comment by coz-m** [comment]
ご指摘ありがとうございました（遅くなって申し訳ありません）。
https://github.com/coz-m/MPLUS_FONTS/blob/master/obsolete/mplus-TESTFLIGHT-063b.tar.gz
に修正済みフォントファイルを用意しました。ご自由にお使いください。

**Comment by nai-kon** [comment]
迅速なご対応ありがとうございます！
