### ISSUE TITLE
Download links from site to this repository are 404 

### ISSUE THREAD

**Issue by TiagoJSilva** [coz-m/MPLUS_FONTS#6]
Yes, I realize submitting an issue like this might be a stretch, considering that a few days ago you were building the first font at fonts/ttf, so of course there's no link to https://github.com/coz-m/MPLUS_FONTS/tree/master/fonts/webfonts-1, for example. 
But in the meantime, could you please put a notice on the website that the download links are not available yet?

I'm trying to find a replacement for Montserrat and the Mplus family seems very interesting. Thank you for your work.

**Comment by coz-m** [comment]
Thank you for your advice. It's late, but I changed the font link destination in the website.
https://mplusfonts.github.io/#download
